name: GitHub Actions Demo & Java CI with Maven
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [ push ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - run: echo " Secret revealed ! ${{ secrets.DATASOURCE_USR }} "
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Npm Dependencies
        run: |
          cd grove-webapp
          npm install
      - name: Npm Build
        run: |
          cd grove-webapp
          npm run build:prod

      - run: echo "Now install JDK19 and then try to run a maven command."
      - name: Set up JDK19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven
      - name: Verify with Maven
        run: mvn -B verify --file pom.xml
      - run: echo "Maven will now run VERIFY."
#        run: mvn -B package --file pom.xml -DskipTests -Dspring-boot.run.arguments="--spring.datasource.username=${{ secrets.DATASOURCE_USR }} --spring.datasource.username=${{ secrets.DATASOURCE_PWD }}"
